language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install --upgrade -r requirements.txt -r requirements-dev.txt"
# command to run tests
script:
  - make test